params
[
	["_killer", nil],
	["_killed", nil]
];

_messagesPvE =
[
	"%1 se volvio puto",
	"%1 vio una mujer...",
	"%1 ahora es judio",
	"%1 debuto con un travesti",
	"%1 fue tocado por el capitan Goce",
	"%1 fue groomeado... (al igual que SrCobayo)",
	"Dopela lleno de crema a %1",
	"%1 se sento en la torta",
	"el Ciruja le dijo inutil a %1",
	"le acabaron en la boca a %1",
	"%1 dijo uwu",
	"%1 se volvio furro",
	"%1 se cayo de un 5to piso",
	"%1 se murio al igual que su papá.",
	"%1 pago Winrar",
	"sos un fraca %1",
	"%1 se olvido la cartulina",
	"%1 se murio",
	"%1 esta jugando a las cartas con Menem",
	"%1 tiene informacion que podria llevar al arresto de CFK",
	"%1 fue nismeado",
	"a %1 lo balacearon los municipales",
	"%1 se fue al cielo",
	"a %1 le dieron un vuelo de libertad",
	"%1 ahora es parte de los 30.000",
	"%1 ahora es parte de Yaciretá",
	"a %1 le dio un bobazo",
	"Dopela le enseñó la crema a %1",
	"%1 le nego una empanada al Ciruja",
	"%1 no te subas al helicoptero",
	"%1 fue aplastado por la panza de Renolito",
	"el Ciruja le cirujeo los organos a %1",
	"mejor adentro que afuera %1",
	"%1 ahora esta en el cielo",
	"%1 se fue para abajo",
	"a %1 le explicaron las tablas de multiplicar",
	"%1 pago el premium en War Thunder",
	"a %1 lo subieron a un tren",
	"%1 conocio a Lezkano",
	"%1 encontro la carpeta de CP de Nikolas",
	"%1 le tuvo que explicar como usar la PC a Feanor",
	"%1 se volvio milsimer",
	"%1 voto a Milei",
	"%1 es peronista",
	"%1 es chileno",
	"%1 invirtio en $LIBRA",
	"%1 no desayuno"
];
_messagesPvP = 
[
	"%1 mandó a las 6 noches con Dopela a %2",
	"%1 aplastó con sus nalgas a %2",
	"%1 le comentó el precio del dólar a %2",
	"%1 se culeó a %2",
	"%1 le explicó el lore de Warhammer a %2",
	"%1 se yiffeó a %2",
	"%1 puso a hacer la noni a %2",
	"%1 demásió a %2",
	"%1 dejó inconsciente a %2",
	"%1 nismeó a %2",
	"%1 manoseó a %2",
	"%1 le dio un beso en la boca a %2",
	"%1 le sacó la lengua a %2",
	"%1 le tocó la cola a %2",
	"%1 está disparando, deberías agacharte %2...",
	"%1 es fan del lolicon, cuidado %2",
	"%1 le dijo milsimer a %2",
	"%1 le tiró el cuerito a %2",
	"%1 frenó las funciones vitales de %2",
	"%1 dividió por cero a %2",
	"%1 le mostró una pala a %2",
	"%1 le vació un cargador a %2",
	"%1 lo mandó con Fraujo a %2",
	"%1 procedió a %2",
	"%1 lo mandó con Cobayo a %2",
	"%1 le rompió el culo a %2",
	"%1 se robó la fibra óptica de %2",
	"%1 lo obligó a chuparle las patas mugrientas antes de matarlo a %2",
	"%1 le rompió el ano a %2",
	"%1 mandó a Bolivia a %2",
	"%1 se masturbó con los intestinos de %2",
	"%1 le cosió el ano a %2",
	"%1 atrapó en su prepucio a %2",
	"%1 le rompió la cabeza a %2",
	"%1 le sacó el mosquito de la cabeza a %2",
	"%1 violó el cráneo abierto de %2",
	"%1 se chapó a %2",
	"%1 le mostró una hembra a %2",
	"%1 convirtió en femboy a %2",
	"%1 le metió un Rexona a %2 en el orto",
	"%2 le comió los huevos a %1",
	"%2 fue penetrado por %1",
	"%2 le hicieron rape4fun de la mano de %1",
	"%1 x %2",
	"%2 fue empujado de un 8vo piso por %1",
	"%2 fue asaltado sexualmente por %1",
	"%1 le violó la garganta a %2",
	"%1 cumeó a %2",
	"%1 mandó a la Shell a %2",
	"%1 mandó a las 6 noches con Fraujo a %2",
	"%1 mandó a las 5 noches con Nikolas a %2",
	"%1 mandó a las 6 noches con SrCobayo a %2",
	"%1 le mostró el PDF de las personalidades de Cobayo a %2",
	"%1 le preguntó si le gusta la pija a %2 (respondió sí)",
	"%1 negreó a %2",
	"%1 le puso un rufie en la bebida a %2",
	"%1 le recetó Mitrozon600 a %2",
	"%1 > %2",
	"%1 hizo jabón a %2",
	"%1 le dijo ricotero a %2",
	"%1 usó de onahole a %2",
	"%1 le enseñó cuántos pares son 3 botas a %2",
	"%1 levantó con el capo a %2",
	"%1 le dijo subhumano a %2",
	"%1 le corrió la bombacha a %2",
	"%1 le movió los intestinos a %2",
	"%1 le habló feo a %2",
	"%1 miró feo a %2",
	"%1 se enfiestó en %2",
	"%1 lo mandó a la panadería a %2",
	"Dopela le enseñó a %1 cómo llenar de crema a %2",
	"%1 le dijo gordo puto a %2",
	"%1 le metió un dedo en el culo a %2",
	"%1 se apoyó a %2",
	"%1 le dijo trolo a %2",
	"%1 le dijo faggot a %2",
	"%1 le dio por el orto a %2",
	"%1 le mandó CP a %2",
	"%1 enamoró a %2",
	"%1 le mostró el pitulín a %2",
	"%1 lo hizo aka a %2",
	"%1 le dijo tucumano a %2",
	"%1 hizo señorita a %2",
	"%1 le dijo mono a %2",
	"%1 le dijo iletrado a %2",
	"%1 acusó de ucraniano a %2",
	"%1 mandó a jugar Roblox a %2",
	"%1 mandó a dormir a %2",
	"%2 cayó en la estafa cripto de %1",
	"%1 timbeó con la vida de %2",
	"%1 cuckeó a %2",
	"%1 volvió judío a %2",
	"%1 acusó de violín a %2"
];
if (_killer in playableUnits) then
{
	format [selectRandom _messagesPvP, name _killer, name _killed] remoteExec ["systemChat"]
}
else
{
	format [selectRandom _messagesPvE, name _killed] remoteExec ["systemChat"]
};

true